### ISSUE TITLE
v0.6.2 Results in Error

### ISSUE THREAD

**Issue by appleplectic** [Zodsmar/SeedSearcherStandaloneTool#106]
New here, just found this repo (amazing work, by the way). However, using the newest release - v0.6.2, adding 1.17 support, gives me no output running the executable. I then tried the jar file, getting this error when running the jar file from the command line:

```
C:\Users\username>java -jar "C:\Users\username\Downloads\sassa-v0.6.2.jar"
java.lang.reflect.InaccessibleObjectException: Unable to make boolean java.lang.reflect.AccessibleObject.setAccessible0(boolean) accessible: module java.base does not "opens java.lang.reflect" to unnamed module @2c4221d2
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.jfoenix.adapters.ReflectionHelper.<clinit>(ReflectionHelper.java:48)
        at com.jfoenix.skins.JFXTextFieldSkin.<init>(JFXTextFieldSkin.java:59)
        at com.jfoenix.controls.JFXTextField.createDefaultSkin(JFXTextField.java:69)
        at javafx.scene.control.Control.doProcessCSS(Control.java:897)
        at javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
        at javafx.scene.Parent.doProcessCSS(Parent.java:1397)
        at javafx.scene.Parent.access$400(Parent.java:79)
        at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
        at javafx.scene.Parent.doProcessCSS(Parent.java:1397)
        at javafx.scene.Parent.access$400(Parent.java:79)
        at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
        at javafx.scene.Parent.doProcessCSS(Parent.java:1397)
        at javafx.scene.Parent.access$400(Parent.java:79)
        at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
        at javafx.scene.Parent.doProcessCSS(Parent.java:1397)
        at javafx.scene.Parent.access$400(Parent.java:79)
        at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
        at javafx.scene.Parent.doProcessCSS(Parent.java:1397)
        at javafx.scene.Parent.access$400(Parent.java:79)
        at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.scene.control.Control.doProcessCSS(Control.java:900)
        at javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
        at javafx.scene.Parent.doProcessCSS(Parent.java:1397)
        at javafx.scene.Parent.access$400(Parent.java:79)
        at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
        at javafx.scene.Parent.doProcessCSS(Parent.java:1397)
        at javafx.scene.Parent.access$400(Parent.java:79)
        at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
        at javafx.scene.Parent.doProcessCSS(Parent.java:1397)
        at javafx.scene.Parent.access$400(Parent.java:79)
        at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
        at javafx.scene.Parent.doProcessCSS(Parent.java:1397)
        at javafx.scene.Parent.access$400(Parent.java:79)
        at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.scene.control.Control.doProcessCSS(Control.java:900)
        at javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
        at javafx.scene.Parent.doProcessCSS(Parent.java:1397)
        at javafx.scene.Parent.access$400(Parent.java:79)
        at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
        at javafx.scene.Node.processCSS(Node.java:9529)
        at javafx.scene.Scene.doCSSPass(Scene.java:569)
        at javafx.scene.Scene.preferredSize(Scene.java:1745)
        at javafx.scene.Scene$2.preferredSize(Scene.java:393)
        at com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
        at javafx.stage.Window$12.invalidated(Window.java:1086)
        at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
        at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
        at javafx.stage.Window.setShowing(Window.java:1174)
        at javafx.stage.Window.show(Window.java:1189)
        at javafx.stage.Stage.show(Stage.java:273)
        at sassa.main.mainApp.start(mainApp.java:52)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        at java.base/java.lang.Thread.run(Thread.java:831)
Exception in Application start method
```

I'm on Windows 10, with Java 8 installed. v0.6.1 and lower work perfectly fine, but v0.6.2 seemed to break it. Since I'm not familiar with Java (Python programmer here), there's not much I can do...

Appreciate the help!

**Comment by Zodsmar** [comment]
Yeah, I added a new dependency. I'm trying to find a solution for it. However 1.17 and 1.16 world gen is Identical so using 0.6.1 will give you 1.17 seeds totally fine! :)

**Comment by shane-smith** [comment]
Having issues with 0.6.2 as well, on both Windows 10 and macOS 11.2.2

It's a different stack trace, though. Is this another symptom of the same issue, or unrelated?

**Windows**
Simply fails to launch. Attempted both the EXE and the JAR file.

**macOS**
Using the JAR file.
```
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by xanderk1** [comment]
To fix: Download Java 16, I use https://adoptopenjdk.net/ (Hotspot). Then open powershell (shift + right click in the same folder as .jar / .exe) then type "java -jar --illegal-access=permit .\sassa-v0.6.2.jar" To launch the program!

**Comment by Zodsmar** [comment]
Uploaded v0.6.3 should fix the issues.
