### ISSUE TITLE
Exception prevents use of finder

### ISSUE THREAD

**Issue by emtes** [Zodsmar/SeedSearcherStandaloneTool#60]
Hi!

When I try to search for seeds (regardless of settings) I get the following error logged to my shell

```
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: kaptainwutax/mathutils/util/Mth
        at kaptainwutax.biomeutils.layer.LayerCache.<init>(LayerCache.java:14)
        at kaptainwutax.biomeutils.layer.BiomeLayer.<init>(BiomeLayer.java:18)
        at kaptainwutax.biomeutils.layer.BiomeLayer.<init>(BiomeLayer.java:30)
        at kaptainwutax.biomeutils.layer.BiomeLayer.<init>(BiomeLayer.java:36)
```

There is more so let me know if would be useful. When I try it with just one thread it says it considered 1 seed and then this error comes up. If I try to use 6 threads it says it looked at 6 seeds but then this error comes and it doesn't do anything.

I followed steps on Wiki to use this on my Ubuntu-based Linux distro. It worked a couple of months ago, but not ever since pulling and trying this week.

Thanks

![seed-finder-log](https://user-images.githubusercontent.com/54204155/93407961-6fd57e00-f861-11ea-9fa0-810e44f7972f.png)

**Comment by RedSparr0w** [comment]
ref #56
