### ISSUE TITLE
Java Class Imcompatibility Issues

### ISSUE THREAD

**Issue by Caleb-JC-Hussey** [Zodsmar/SeedSearcherStandaloneTool#69]
So, I tried to run the jar file, and it didn't run. I then ran it in a terminal to see what was happening. Apparently, my Java version was too old. "Ok, I'll just update it then." I was already on the most recent update for my operating system: Java 14. It would be really nice if this was made in an industry standard version. I can't easily install 15 without breaking java dependencies for other packages I have installed on my system. I run Manjaro KDE (arch linux derivative), and I use the Manjaro repositories, and the AUR. Java 14 is the best I can do.

`[calebh@Caleb-ManjaroKDE ~]$ cd Desktop
[calebh@Caleb-ManjaroKDE Desktop]$ java -jar sassa-v0.6.0.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: javafx/application/Application has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sassa.main.Main.main(Main.java:17)
[calebh@Caleb-ManjaroKDE Desktop]$ `

**Comment by Caleb-JC-Hussey** [comment]
NVM it's my system.
