### ISSUE TITLE
Sassa 0.6.0 jar can't be run on MacOS Big Sur update

### ISSUE THREAD

**Issue by debottendev** [Zodsmar/SeedSearcherStandaloneTool#70]
I can't open the jar file on big sur. It was possible on Catalina.

 `Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:835)`

**Comment by Zodsmar** [comment]
I need to look into this.

**Comment by Zodsmar** [comment]
Gonna be releasing the next version very soon, Ill do the build I normally do and if this is still an issue Ill try some different stuff. Just a heads up

**Comment by PeacePlays** [comment]
I can confirm I am running the newest version on an M1 Mac (Mac OS 11) using Minecrafts included Java version.

I have been starting it from the Terminal using: ~/Library/Application\ Support/minecraft/runtime/jre-x64/jre.bundle/Contents/Home/bin/java -jar 

You use a space at the end of that command and then drag and drop the Jar file into the terminal window and hit enter.

**Comment by Zodsmar** [comment]
I will do some testing before I release the next major update.

**Comment by Yuanyang-Che** [comment]
This happened to me as well. I am trying to run Sassa 0.6.2.jar on an intel MacBook Pro with Catalina (MacOS 15). Tried JDK version 11, 13, 15, and 16.  All of them gives the same(the exception line number might be off for a few lines).

Here is the exception when running `java -jar sassa-v0.6.2.jar` in JDK 11   

`Graphics Device initialization failed for :  es2, sw
 Error initializing QuantumRenderer: no suitable pipeline found
 java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
 Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
 Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by Yuanyang-Che** [comment]
I finally got it to work, by downloading the source code and run it in intellij.

**Comment by devjta** [comment]
My god how broken is that tool... Its unstartable in Linux. Its un-compile able..

**Comment by matriarx** [comment]
I'm using intel big sur and everything works just fine.  However I'm running it through intellij so not sure if that's making a difference (it's likely that the distributable jar doesn't work everywhere if it was built on a specific machine), but it'll work correctly if you build it on your own machine from source.  

- Clone this repo to your local computer.  
- Install intellij and open a project (this repo, wherever you saved it).  
- Make sure that your "preferences > build, execution & deployment > build tools > gradle" JVM is set to v11.  
- Make sure that your "file > project structure > project settings > project" is using sdk v11.  
- Build everything (or configure to run "buildAll").  
- Finally edit configuration and add a new gradle project with command "run", then just run it.
